"""empty message

Revision ID: 48d6a3fff8f1
Revises: 42864254c667
Create Date: 2015-03-29 18:00:34.408702

"""

# revision identifiers, used by Alembic.
revision = '48d6a3fff8f1'
down_revision = '42864254c667'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('can_edit', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_edit')
    ### end Alembic commands ###
